# Use latest Node LTS to build
FROM node:lts as builder
# Copy Vue.js code
WORKDIR /src/
COPY ./webui ./webui
WORKDIR /src/webui/
### Build Vue.js into plain HTML/CSS/JS
RUN yarn run build-prod
### Create final container
FROM nginx:stable
### Copy the (built) app from the builder image
COPY --from=builder /src/webui/dist /usr/share/nginx/html